### ISSUE TITLE
Any plans on porting to 3.10?

### ISSUE THREAD

**Issue by ghost** [hdni/Phosphene#6] opened 2013-10-15 20:02 UTC

**Comment by hdni** [comment] 2013-10-19 17:50
I'm working on it when I have the time, but there are some little things I have to figure out. Don't worry though, it'll be released soon. That means more studying the original Adwaita theme!
As of now, what's keeping me from releasing the 3.10 version are these issues:
- ~~That pesky arrow next to the application name in the app menu for the Shell~~
- Gnome Music's sidebar (and to some extent its "load more" buttons). I might drop this because the program isn't really ready yet.
- ~~The Tweak Tool's "remove" buttons in the extension menu have white text (on a white bg). They're a new type of button which for some reason ignore the general button styling on .button.~~
- ~~Windows with CSS borders (ie the new ones with inline controls) are stuck with a 4px border radius in their corners, probably needs a different implementation than what I'm doing now.~~ Now 2px in all corners, so it's fixed.
- ~~Those windows' toolbars don't have rounded corners, which messes with my initial intention of having toolbars with four rounded corners so they look like they're floating in the window~~  ~~Nautilus's toolbar still doesn't have rounded corners on the bottom.~~ Fixed with a border image.
- (Optionally) I wanted to design the inline close button to set it apart a bit more, but I can't find a good way to do so
- Some minor alignment and color inconsistencies

**Comment by CamilleScholtz** [comment] 2013-10-20 13:31
I can't wait for the 3.10 version :)

About the dropdown arrows, I don't know how you removed them, but here is an extension you could also try: https://github.com/mpdeimos/gnome-shell-remove-dropdown-arrows

About the new windows borders, how did you do it? I tried it with "outline: 4px solid #fff" in ".window-frame", but that gives the border a radius of 4px like you said.

**Comment by hdni** [comment] 2013-10-20 15:46
Hey, I didn't know you'd moved to Gnome. I hope you're liking it.
Wish I knew about that extension sooner! Getting rid of them involved racking my brain and some hacks to the shell theme:

```
/* Hack to remove arrow from appMenu */
.panel-status-menu-box {
    font-size: 0;
}

.panel-status-menu-box *:last-child {
    font-size: 8pt;
}

/* Aggregate menu in the top right */

/* Hack to remove triangle after the icons */
.panel-status-indicators-box {
    font-size: 0; 
    spacing: 0;
}

.panel-status-indicators-box .system-status-icon {
    font-size: 8pt;
}
```

The window borders are pretty weird too, their border radius is equal to the outline's width and that can't be modified. So I had to set an outline of 2px to get the desired result, and then add a 2px border around the title/toolbars to keep a 4px padding around those. If I add a 4px border around the title bars with no outline instead, I can't round the two bottom corners.
I also needed some other trickery so the title bars could have rounded corners without a black background where those corners were before... 
The downside to the 2px outline/2px border combo is that elements inside those windows only have a 2px border from the edge, so they're not aligned with the toolbar (see the Tweak Tool in pic). But I don't think I can do any better, let me know if you find something else!

![2013-10-20](https://f.cloud.github.com/assets/3179152/1368412/59094cc2-399d-11e3-86b8-b77188b88c05.png)

**Comment by CamilleScholtz** [comment] 2013-10-20 16:33
> Hey, I didn't know you'd moved to Gnome. I hope you're liking it.

Yeah I couldn't stand the buggy, outdated programs I used on windows (bblean, truetransparency) anymore, So I switched to Manjaro Linux. The only thing that held me back from making the switch was basically Photoshop, but now on Linux I use Krita, which is also really good! 

The screenshot looks great, I have a few questions about the extension you use, where did you get "media player indicator mod" and "move clock"? I can't find them on the extension page or on github... 

> let me know if you find something else! 

![alt text](http://a.pomf.se/1Hi0.png) 
Like the image linked above shows, your gtk shadows have a hard ugly edge, I also had this problem, you can fix it by doing this:

change

```
.window-frame {
--> border-color: darker(@theme_base_color);
??  border-radius: 10px 10px 0 0;
--> border-width: 1px;
--> border-style: solid;
...
```

to

```
.window-frame {
--> border: 3px solid #fff;
??  border-radius: 2px;
...
```

I'm not sure what "border-radius" actually does, but I just changed it to two.

And a suggestion/tip, this is not really .css related but whatever, you should look into https://addons.mozilla.org/En-us/firefox/addon/close-button/ to make firefox more native, the addon basically ads a close button, you could style it to look like the new gnome close buttons. Oh and maybe _maybe_ consider removing the old minimize/maximize/close buttons to keep things consistent.

**Comment by hdni** [comment] 2013-10-20 17:50
> Like the image linked above shows, your gtk shadows have a hard ugly edge, I also had this problem, you can fix it by doing this

Much appreciated. That did work, I had commented those lines because I didn't see their effect. The border radius does what you would think, except it doesn't seem to work for the bottom corners. I had to set it to 0 so the title bars had proper rounded corners with a white bg.

> I have a few questions about the extension you use, where did you get "media player indicator mod" and "move clock"

The first one is the Media player indicator you can find on the extensions page, which I modified a bit. I removed the status icons in the panel, the icon next to the player name, the repeat (?) icon next to the elapsed time, and tweaked the style sheet a bit (colors, padding, font sizes, the close icon, etc.)
The second is the Frippery Move Clock extension that isn't available anymore, which I ported (read: added "3.10" in the metadata) and modified so the clock was moved completely to the right instead of to the left of the aggregate menu.
If you're interested in any of those, I could put them on here. 

![screenshot from 2013-10-20 13 27 58](https://f.cloud.github.com/assets/3179152/1368561/f60d95fe-39ad-11e3-8d3e-890c7cf79da8.png)

Your idea for Firefox is a pretty good one, I'll consider it. I also have an issue with the Phosphene user style and FxChrome 25.1 on Nightly and Firefox which I need to look into.
On the other hand, I don't really want to remove the controls for normal windows. I think what they add to the theme is pretty important, because their design references other parts of Phosphene and sets it apart, too. The inline controls don't seem to be tightly integrated in Gnome yet either; I'd think about it if every GTK 3 program had them, but that's not the case (gedit and evolution are core Gnome programs that haven't been redesigned yet, for example). I understand your point about inconsistency, but that's not something I want to deal with for now, since the Gnome team hasn't sorted it out either — as can be seen in the default Adwaita theme.
Those controls are really cool, and I have different ideas of what I want to do with them, but I think I'll keep those for Flèche, since its window decorations are simpler.

And I'll definitely have to try Krita! I've been making do with Gimp and it's fine for simple things (which is pretty much all I do anyway), but Krita looks interesting.

**Comment by CamilleScholtz** [comment] 2013-10-20 18:02
> If you're interested in any of those, I could put them on here. 

Yeah that would be sweet.

> I also have an issue with the Phosphene user style and FxChrome 25.1 on Nightly and Firefox which I need to look into.

I also had some problems with firefox nightly, that's why is switched back to release firefox, it's not like there is much of a difference between the two.

> I think what they add to the theme is pretty important

I agree with this, it's kind of the trademark of this theme but it was just an idea, I'll probably experiment with it a bit  myself once you realese the 3.10 version of Phosphene.

> And I'll definitely have to try Krita! 

Krita is really cool, but it is (a lot) more painter oriented than gimp, I still use gimp for simple edits. the only downside to krita is the shit ton of kde dependencies. and if you want to change the theme to something useable you NEED to install kdebase. it's only +-200mb, but it's still kinda annoying because I'm ocd about "bloat".

One more thing, I noticed the switch buttons look kinda blurry, they used to be sharper iirc. They probably changed the size of the switch buttons and the image probably gets scaled a bit.

**Comment by hdni** [comment] 2013-10-20 18:55
Just uploaded both extensions, tell me if there are any issues.

> I also had some problems with firefox nightly, that's why is switched back to release firefox, it's not like there is much of a difference between the two.

~~I tried that, but it still doesn't work for some reason. I'll try to figure it out.~~ Fixed. 
![screenshot from 2013-10-20 13 57 25](https://f.cloud.github.com/assets/3179152/1368717/2b8893c2-39b9-11e3-93c4-2e67cb4f5b38.png)

> One more thing, I noticed the switch buttons look kinda blurry, they used to be sharper iirc. They probably changed the size of the switch buttons and the image probably gets scaled a bit.

Good eye, it's fixed now
Thanks a lot for the help so far.

**Comment by evanpurkhiser** [comment] 2013-10-21 13:29
I don't have anything to contribute here, but I just wanted to let you know that you can actually use [special GH markdown](https://help.github.com/articles/github-flavored-markdown#task-lists) syntax to create check-box item lists like this:
- [ ] An un-finished item
- [x] A finished item

Just wanted to let you know since I saw you crossing out items in your first response!

**Comment by hdni** [comment] 2013-10-21 23:08
That's actually pretty useful, thanks for pointing it out. It didn't cross my mind when I was writing the post.

**Comment by hdni** [comment] 2013-10-22 01:01
I just pushed the 3.10 version, please tell me if you find any additional issues. I am aware of the one that was what I mentioned above:

> The downside to the 2px outline/2px border combo is that elements inside those windows only have a 2px border from the edge, so they're not aligned with the toolbar (see the Tweak Tool in pic)

I did fix it for Nautilus, but I'm not sure I can fix it for the others. I think this is a case of trying to do something the developers didn't think of.

I'm also working on a new browser design with different tabs and padding adjusted to the new Nautilus, there are just some weird glitches I need to sort out which I'm not sure are caused by the style itself.

![screenshot from 2013-10-21 21 12 59](https://f.cloud.github.com/assets/3179152/1377965/41fc3d94-3ab7-11e3-9b75-6f4f2f400273.png)

**Closed as completed by hdni** 2013-10-22 01:01 UTC
